 S_ERR [0x00002e84] [2018-05-27 12:00:48,839] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,840] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,840] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,841] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,841] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,841] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,842] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,842] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,842] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,843] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,843] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,843] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,844] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,844] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,844] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,845] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,845] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,845] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,846] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,846] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,846] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,847] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,847] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,847] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,848] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,848] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,848] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,849] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,849] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,850] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,850] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,851] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,851] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,851] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,852] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,852] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,852] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,853] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,853] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,853] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,854] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,854] - SystemError: error return without exception set
  WARN [0x00002e84] [2018-05-27 12:00:48,854] - e:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.13 seconds
 S_ERR [0x00002e84] [2018-05-27 12:00:48,854] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,855] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,855] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,084] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,088] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,089] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,090] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,091] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,092] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,093] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,093] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,094] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,094] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,095] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,095] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,096] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,097] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,097] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,098] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,099] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,099] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,100] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,100] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,101] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,102] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,102] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,103] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,103] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,104] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,104] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,105] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,106] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,106] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,107] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,107] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,108] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,108] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,110] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,110] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,111] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,111] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,112] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,112] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,113] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,113] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,114] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,115] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,115] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,116] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,117] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,117] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,118] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,119] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,119] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,119] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,120] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,120] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,120] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,121] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,121] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,121] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,122] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,122] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,123] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,123] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,123] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,124] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,124] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,124] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,125] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,125] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,125] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,126] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,126] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,126] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,383] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,386] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,387] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,389] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,390] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,391] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,393] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,394] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,395] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,396] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,398] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,399] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,401] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,402] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,403] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,404] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,406] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,406] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,408] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,409] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,410] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,411] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,413] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,414] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,415] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,416] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,416] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,418] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,419] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,419] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,420] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,421] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,422] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,423] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,424] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,425] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,426] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,427] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,427] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,429] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,430] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,430] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,431] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,433] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,433] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,434] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,435] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,436] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,437] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,438] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,439] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,440] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,441] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,441] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,442] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,443] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,444] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,445] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,446] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,446] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,447] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,448] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,449] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,450] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,450] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,450] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,451] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,452] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,452] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,452] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,453] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,453] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,454] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,454] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,455] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,455] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,456] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,456] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,456] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,457] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,457] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,458] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,458] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,458] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,459] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,459] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,460] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,460] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,461] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,461] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,461] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,462] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,462] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,463] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,463] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,463] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,464] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,464] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,465] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,465] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,466] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,466] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,466] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,467] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,467] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,468] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,468] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,468] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,469] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,470] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,470] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,470] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,474] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,474] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,475] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,477] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,477] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,502] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,503] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,503] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,504] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,505] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,505] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,506] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,506] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,506] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,507] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,507] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,507] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,508] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,508] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,509] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,509] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,510] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,510] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,510] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,511] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,511] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,512] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,512] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,512] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,513] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,513] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,513] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,514] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,514] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,515] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,515] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,515] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,516] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,516] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,517] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,517] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,517] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,518] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,518] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,518] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,519] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,519] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,520] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,520] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,520] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,521] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,521] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,521] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,522] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,522] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,523] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,523] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,524] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,524] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,524] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,525] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,525] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,525] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,526] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,526] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,526] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,527] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,527] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,527] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,528] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,528] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,528] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,529] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,529] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,529] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,530] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,530] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,530] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,531] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,531] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,531] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,532] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,532] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,532] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,533] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,533] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,533] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,534] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,534] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,534] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,535] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,535] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,535] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,536] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,536] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,536] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,537] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,537] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,538] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,538] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,538] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,539] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,539] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,539] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,540] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,540] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,540] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,541] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,541] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,541] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,542] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,542] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,542] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,543] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,543] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,543] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,544] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,544] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,544] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,545] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,545] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,545] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,546] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,546] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,546] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,547] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,547] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,547] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,548] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,548] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,548] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,549] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,549] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,549] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,550] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,550] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,550] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,551] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,551] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,551] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,552] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,552] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,553] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,553] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,554] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,554] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,902] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,903] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,903] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,904] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,905] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,905] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,906] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,906] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,907] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:49,908] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:49,908] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:49,909] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,143] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:50,145] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:50,147] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,148] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:50,150] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:50,151] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,152] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:50,154] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:50,154] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,156] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:50,157] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:50,158] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,160] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:50,161] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:50,162] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,984] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:50,986] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:50,987] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,990] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:50,995] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:50,996] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:50,998] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,000] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,001] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,062] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,064] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,064] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,065] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,066] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,066] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,067] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,067] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,068] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,102] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,103] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,104] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,105] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,106] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,106] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,107] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,108] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,108] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,109] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,109] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,110] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,142] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,144] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,144] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,404] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,406] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,407] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,409] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,412] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,413] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,415] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,417] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,418] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,421] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,423] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,424] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,564] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,566] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,567] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,569] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,572] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,573] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,576] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,578] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,579] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,581] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,583] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,584] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:51,587] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:51,589] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:51,589] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,163] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,164] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,165] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,244] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,246] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,247] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,250] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,252] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,253] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,255] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,257] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,259] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,261] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,263] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,264] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,267] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,269] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,270] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,271] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,272] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,272] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,273] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,274] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,275] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,276] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,277] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,277] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,278] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,279] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,279] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,280] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,281] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,282] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,444] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,446] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,447] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,463] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,465] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,466] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,468] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,469] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,480] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,483] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,484] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,485] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,487] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,488] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,489] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,543] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,544] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,545] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:52,547] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:52,550] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:52,551] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,403] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,406] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,407] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,443] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,445] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,445] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,447] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,448] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,449] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,451] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,452] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,452] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,463] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,464] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,465] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,467] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,468] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,469] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,483] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,485] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,486] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,488] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,489] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,490] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,502] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,503] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,503] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,504] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,504] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,504] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,602] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,603] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,603] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,664] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,666] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,667] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,670] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,672] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,673] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,675] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,678] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,678] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,679] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,680] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,680] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:53,681] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:53,681] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:53,682] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,802] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,803] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,804] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,805] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,806] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,807] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,841] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,842] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,842] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,843] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,844] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,844] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,862] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,865] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,866] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,868] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,870] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,871] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,882] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,883] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,883] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,885] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,886] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,887] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,902] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,903] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,904] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,905] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,906] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,906] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,907] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,908] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,908] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,909] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,909] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,910] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,910] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,911] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,911] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,911] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,912] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,912] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,913] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,913] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,913] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:54,914] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:54,914] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:54,914] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:57,863] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:57,864] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:57,864] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:57,865] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:57,866] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:57,866] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:57,867] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:57,868] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:57,869] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,064] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,067] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,068] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,070] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,073] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,073] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,076] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,078] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,079] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,081] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,084] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,085] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,088] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,090] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,091] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,094] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,096] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,097] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,099] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,101] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,106] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,143] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,144] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,145] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,146] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,148] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,148] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,150] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,151] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,152] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,153] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,154] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,155] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,156] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,157] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,157] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,158] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,159] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,160] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,161] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,162] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,162] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,203] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,206] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,207] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,242] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,243] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,244] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,245] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,246] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,246] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,343] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,344] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,344] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,345] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,346] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,347] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,348] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,348] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,349] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,350] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,350] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,351] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,604] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,606] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,607] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,663] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,665] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,666] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,703] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,705] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,706] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,707] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,709] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,709] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,711] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,712] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,713] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,743] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,744] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,745] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,782] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,783] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,783] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,784] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,785] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,785] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:59,802] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:59,803] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:59,803] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:01:25,804] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:01:25,807] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:01:25,808] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:01:26,103] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:01:26,104] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:01:26,105] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:01:31,805] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:01:31,808] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:01:31,809] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:01:31,904] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:01:31,907] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:01:31,908] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:01:33,504] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:01:33,505] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:01:33,506] - SystemError: error return without exception set
  INFO [0x00002e84] [2018-05-27 12:01:33,803] - Logger::registerLogWatcher: addr=192.168.0.104:51210 is successfully!
 S_ERR [0x00002e84] [2018-05-27 12:01:33,808] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:01:33,810] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:01:33,811] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:01:50,984] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:01:50,986] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:01:50,987] - SystemError: error return without exception set
  INFO [0x0000364c] [2018-05-27 12:02:07,045] - 
  INFO [0x0000364c] [2018-05-27 12:02:07,045] - -----------------------------------------------------------------------------------------


  INFO [0x0000364c] [2018-05-27 12:02:07,045] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x0000364c] [2018-05-27 12:02:07,045] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x0000364c] [2018-05-27 12:02:07,046] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x0000364c] [2018-05-27 12:02:07,048] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51226 )
  INFO [0x0000364c] [2018-05-27 12:02:07,048] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51226, SOMAXCONN=5.
  INFO [0x0000364c] [2018-05-27 12:02:07,049] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51227 )
  INFO [0x0000364c] [2018-05-27 12:02:07,049] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51227, SOMAXCONN=5.
  INFO [0x0000364c] [2018-05-27 12:02:07,053] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 11365. PID: 14332 ----
  INFO [0x0000364c] [2018-05-27 12:02:07,053] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x0000364c] [2018-05-27 12:02:07,053] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x0000364c] [2018-05-27 12:02:07,053] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x0000364c] [2018-05-27 12:02:07,183] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x0000364c] [2018-05-27 12:02:07,183] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x0000364c] [2018-05-27 12:02:07,184] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x0000364c] [2018-05-27 12:02:07,187] - Script::install_py_dlls(): PyInit__hashlib
