  INFO root [2018-05-27 11:29:43,022] - 
  INFO root [2018-05-27 11:29:43,036] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:29:43,405] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:29:43,405] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:29:43,405] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:29:44,532] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:29:44,578] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:29:44,583] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50635 )
  INFO root [2018-05-27 11:29:44,584] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50635, SOMAXCONN=128.
  INFO root [2018-05-27 11:29:44,584] - server-configs:
  INFO root [2018-05-27 11:29:44,584] - 	internalAddr : 192.168.0.104:50635
  INFO root [2018-05-27 11:29:44,585] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:29:44,585] - 	componentID : 9000
  INFO root [2018-05-27 11:29:45,420] - Components::findLogger: found logger, addr:192.168.0.104:50629
  INFO root [2018-05-27 11:29:45,421] - Components::addComponent: reset orderLog, uid=4945!
  INFO root [2018-05-27 11:29:45,422] - Components::addComponent[logger], uid=4945, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:29:45,633] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 4945. PID: 12056 ----
  INFO root [2018-05-27 11:29:45,634] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:29:45,665] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:29:45,854] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:29:53,468] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:29:53,632] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:29:53,660] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:29:55,394] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:29:55,513] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:29:55,550] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:29:55,610] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:29:56,340] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:29:57,645] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:29:57,646] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:29:57,826] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:29:57,827] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:29:58,490] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:29:58,491] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:30:04,679] - 
  INFO root [2018-05-27 11:30:04,679] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:30:04,680] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:30:04,680] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:30:04,680] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:30:04,682] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:30:04,682] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:30:04,683] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50652 )
  INFO root [2018-05-27 11:30:04,683] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50652, SOMAXCONN=128.
  INFO root [2018-05-27 11:30:04,684] - server-configs:
  INFO root [2018-05-27 11:30:04,684] - 	internalAddr : 192.168.0.104:50652
  INFO root [2018-05-27 11:30:04,684] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:30:04,684] - 	componentID : 9000
  WARN root [2018-05-27 11:30:05,209] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20540, errorno=10048
  INFO root [2018-05-27 11:30:05,215] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 5088. PID: 12168 ----
  INFO root [2018-05-27 11:30:05,216] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:30:05,216] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:30:05,216] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:30:05,341] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:30:05,341] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:30:05,341] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:30:05,345] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:30:05,345] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:30:05,345] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:30:05,345] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:30:05,380] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:30:05,407] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:30:05,407] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:30:05,408] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:30:05,409] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:30:05,686] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:30:05,686] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:30:12,809] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 11:30:12,861] - Components::findComponents: found logger, addr:192.168.0.104:50648
  INFO root [2018-05-27 11:30:12,862] - Components::addComponent: reset orderLog, uid=5088!
  INFO root [2018-05-27 11:30:12,863] - Components::addComponent[logger], uid=5088, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:30:12,865] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-27 11:30:13,966] - Forwarding logs to logger[192.168.0.104:50648/0/0/0]...
  INFO root [2018-05-27 11:30:26,068] - 
  INFO root [2018-05-27 11:30:26,068] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:30:26,069] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:30:26,069] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:30:26,069] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:30:26,074] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:30:26,075] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:30:26,076] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50670 )
  INFO root [2018-05-27 11:30:26,076] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50670, SOMAXCONN=128.
  INFO root [2018-05-27 11:30:26,076] - server-configs:
  INFO root [2018-05-27 11:30:26,076] - 	internalAddr : 192.168.0.104:50670
  INFO root [2018-05-27 11:30:26,076] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:30:26,076] - 	componentID : 9000
  WARN root [2018-05-27 11:30:26,604] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20182, errorno=10048
  INFO root [2018-05-27 11:30:26,608] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 5157. PID: 12896 ----
  INFO root [2018-05-27 11:30:26,609] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:30:26,609] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:30:26,609] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:30:26,731] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:30:26,732] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:30:26,732] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:30:26,735] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:30:26,735] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:30:26,735] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:30:26,736] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:30:26,763] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:30:26,790] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:30:26,790] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:30:26,792] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:30:26,792] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:30:27,063] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:30:27,064] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:30:34,192] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 11:30:34,266] - Components::findComponents: found logger, addr:192.168.0.104:50671
  INFO root [2018-05-27 11:30:34,267] - Components::addComponent: reset orderLog, uid=5157!
  INFO root [2018-05-27 11:30:34,268] - Components::addComponent[logger], uid=5157, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:30:34,270] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-27 11:30:35,370] - Forwarding logs to logger[192.168.0.104:50671/0/0/0]...
 ERROR root [2018-05-27 11:30:39,020] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:30:39,027] - The following logs sent to logger failed:
  WARN root [2018-05-27 11:30:39,027] - ==> [2018-05-27 11:30:39 019] TCPPacketReceiver::processPendingEvents(192.168.0.104:50671): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:30:39,028] - ==> [2018-05-27 11:30:39 021] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:31:11,872] - 
  INFO root [2018-05-27 11:31:11,872] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:31:11,873] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:31:11,873] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:31:11,873] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:31:11,876] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:31:11,876] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:31:11,877] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50694 )
  INFO root [2018-05-27 11:31:11,878] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50694, SOMAXCONN=128.
  INFO root [2018-05-27 11:31:11,878] - server-configs:
  INFO root [2018-05-27 11:31:11,878] - 	internalAddr : 192.168.0.104:50694
  INFO root [2018-05-27 11:31:11,878] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:31:11,878] - 	componentID : 9000
  INFO root [2018-05-27 11:31:13,581] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 5307. PID: 12928 ----
  INFO root [2018-05-27 11:31:13,581] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:31:13,582] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:31:13,582] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:31:13,712] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:31:13,712] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:31:13,713] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:31:13,716] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:31:13,716] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:31:13,716] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:31:13,716] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:31:13,749] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:31:13,783] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:31:13,783] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:31:13,785] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:31:13,785] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:31:14,093] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:31:14,093] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:31:21,175] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 11:31:21,257] - Components::findComponents: found logger, addr:192.168.0.104:50691
  INFO root [2018-05-27 11:31:21,258] - Components::addComponent: reset orderLog, uid=5307!
  INFO root [2018-05-27 11:31:21,258] - Components::addComponent[logger], uid=5307, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:31:21,259] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 11:31:21,363] - Components::findComponents: found dbmgr, addr:192.168.0.104:50688
  INFO root [2018-05-27 11:31:21,363] - Components::addComponent: reset orderLog, uid=5307!
  INFO root [2018-05-27 11:31:21,364] - Components::addComponent[dbmgr], uid=5307, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:31:21,365] - Components::findComponents: found dbmgr, addr:192.168.0.104:50688
  WARN root [2018-05-27 11:31:22,365] - Forwarding logs to logger[192.168.0.104:50691/0/0/0]...
 ERROR root [2018-05-27 11:32:36,361] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:32:36,366] - The following logs sent to logger failed:
  WARN root [2018-05-27 11:32:36,366] - ==> [2018-05-27 11:32:36 360] TCPPacketReceiver::processPendingEvents(192.168.0.104:50691): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:32:36,366] - ==> [2018-05-27 11:32:36 362] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 11:32:36,421] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50688): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:32:36,423] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:32:36,431] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 11:32:36,432] - onLoginAppShutDown()
  INFO root [2018-05-27 11:32:36,432] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 11:32:36,432] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 11:32:36,432] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:32:36,433] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:32:36,433] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:32:36,433] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:32:36,433] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:32:36,433] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:32:36,433] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:32:36,433] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:32:36,476] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 11:32:36,476] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 11:32:37,676] - 
  INFO root [2018-05-27 11:32:37,676] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:32:37,677] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:32:37,677] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:32:37,677] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:32:37,682] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:32:37,682] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:32:37,683] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50747 )
  INFO root [2018-05-27 11:32:37,683] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50747, SOMAXCONN=128.
  INFO root [2018-05-27 11:32:37,683] - server-configs:
  INFO root [2018-05-27 11:32:37,683] - 	internalAddr : 192.168.0.104:50747
  INFO root [2018-05-27 11:32:37,683] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:32:37,684] - 	componentID : 9000
  WARN root [2018-05-27 11:32:38,217] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20955, errorno=10048
  INFO root [2018-05-27 11:32:38,221] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 5588. PID: 13136 ----
  INFO root [2018-05-27 11:32:38,221] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:32:38,221] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:32:38,221] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:32:38,346] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:32:38,346] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:32:38,347] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:32:38,350] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:32:38,350] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:32:38,350] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:32:38,350] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:32:38,381] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:32:38,409] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:32:38,409] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:32:38,411] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:32:38,411] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:32:38,721] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:32:38,721] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:32:45,812] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 11:32:45,889] - Components::findComponents: found logger, addr:192.168.0.104:50743
  INFO root [2018-05-27 11:32:45,890] - Components::addComponent: reset orderLog, uid=5588!
  INFO root [2018-05-27 11:32:45,890] - Components::addComponent[logger], uid=5588, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:32:45,891] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 11:32:45,995] - Components::findComponents: found dbmgr, addr:192.168.0.104:50741
  INFO root [2018-05-27 11:32:45,995] - Components::addComponent: reset orderLog, uid=5588!
  INFO root [2018-05-27 11:32:45,996] - Components::addComponent[dbmgr], uid=5588, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:32:45,997] - Components::findComponents: found dbmgr, addr:192.168.0.104:50741
  WARN root [2018-05-27 11:32:46,997] - Forwarding logs to logger[192.168.0.104:50743/0/0/0]...
 ERROR root [2018-05-27 11:34:43,104] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:34:43,111] - The following logs sent to logger failed:
  WARN root [2018-05-27 11:34:43,112] - ==> [2018-05-27 11:34:43 103] TCPPacketReceiver::processPendingEvents(192.168.0.104:50743): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:34:43,112] - ==> [2018-05-27 11:34:43 105] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 11:34:43,166] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50741): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:34:43,167] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:34:43,174] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 11:34:43,175] - onLoginAppShutDown()
  INFO root [2018-05-27 11:34:43,175] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 11:34:43,175] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 11:34:43,175] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:34:43,175] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:34:43,175] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:34:43,176] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:34:43,176] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:34:43,176] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:34:43,176] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:34:43,176] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:34:43,184] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 11:34:43,184] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 11:34:44,329] - 
  INFO root [2018-05-27 11:34:44,329] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:34:44,330] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:34:44,330] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:34:44,330] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:34:44,333] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:34:44,333] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:34:44,335] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50812 )
  INFO root [2018-05-27 11:34:44,335] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50812, SOMAXCONN=128.
  INFO root [2018-05-27 11:34:44,335] - server-configs:
  INFO root [2018-05-27 11:34:44,335] - 	internalAddr : 192.168.0.104:50812
  INFO root [2018-05-27 11:34:44,335] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:34:44,335] - 	componentID : 9000
  WARN root [2018-05-27 11:34:44,866] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20347, errorno=10048
  INFO root [2018-05-27 11:34:44,869] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 5999. PID: 5784 ----
  INFO root [2018-05-27 11:34:44,869] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:34:44,870] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:34:44,870] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:34:44,993] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:34:44,993] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:34:44,993] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:34:44,996] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:34:44,996] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:34:44,996] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:34:44,997] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:34:45,024] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:34:45,052] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:34:45,053] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:34:45,055] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:34:45,055] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:34:45,337] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:34:45,338] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:34:52,455] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 11:34:52,471] - Components::findComponents: found logger, addr:192.168.0.104:50810
  INFO root [2018-05-27 11:34:52,471] - Components::addComponent: reset orderLog, uid=5999!
  INFO root [2018-05-27 11:34:52,471] - Components::addComponent[logger], uid=5999, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:34:52,474] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 11:34:52,576] - Components::findComponents: found dbmgr, addr:192.168.0.104:50813
  INFO root [2018-05-27 11:34:52,576] - Components::addComponent: reset orderLog, uid=5999!
  INFO root [2018-05-27 11:34:52,577] - Components::addComponent[dbmgr], uid=5999, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:34:52,577] - Components::findComponents: found dbmgr, addr:192.168.0.104:50813
  WARN root [2018-05-27 11:34:53,578] - Forwarding logs to logger[192.168.0.104:50810/0/0/0]...
 ERROR root [2018-05-27 11:54:57,575] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:54:57,586] - The following logs sent to logger failed:
  WARN root [2018-05-27 11:54:57,586] - ==> [2018-05-27 11:54:57 574] TCPPacketReceiver::processPendingEvents(192.168.0.104:50810): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:54:57,586] - ==> [2018-05-27 11:54:57 576] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 11:54:57,640] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50813): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:54:57,641] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:54:57,651] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 11:54:57,652] - onLoginAppShutDown()
  INFO root [2018-05-27 11:54:57,652] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 11:54:57,652] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:54:57,653] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:54:57,662] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 11:54:57,662] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 11:55:00,443] - 
  INFO root [2018-05-27 11:55:00,444] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:55:00,445] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:55:00,445] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:55:00,445] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:55:00,451] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:55:00,451] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:55:00,454] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50961 )
  INFO root [2018-05-27 11:55:00,454] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50961, SOMAXCONN=128.
  INFO root [2018-05-27 11:55:00,454] - server-configs:
  INFO root [2018-05-27 11:55:00,454] - 	internalAddr : 192.168.0.104:50961
  INFO root [2018-05-27 11:55:00,454] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:55:00,454] - 	componentID : 9000
  INFO root [2018-05-27 11:55:02,187] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 9974. PID: 12624 ----
  INFO root [2018-05-27 11:55:02,188] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:55:02,188] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:55:02,188] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:55:02,313] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:55:02,314] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:55:02,314] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:55:02,317] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:55:02,317] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:55:02,317] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:55:02,318] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:55:02,355] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:55:02,389] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:55:02,389] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:55:02,392] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:55:02,392] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:55:02,699] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:55:02,700] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:55:09,813] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 11:55:09,888] - Components::findComponents: found logger, addr:192.168.0.104:50960
  INFO root [2018-05-27 11:55:09,888] - Components::addComponent: reset orderLog, uid=9974!
  INFO root [2018-05-27 11:55:09,888] - Components::addComponent[logger], uid=9974, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:55:09,890] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 11:55:09,995] - Components::findComponents: found dbmgr, addr:192.168.0.104:50966
  INFO root [2018-05-27 11:55:09,995] - Components::addComponent: reset orderLog, uid=9974!
  INFO root [2018-05-27 11:55:09,996] - Components::addComponent[dbmgr], uid=9974, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:55:09,996] - Components::findComponents: found dbmgr, addr:192.168.0.104:50966
  WARN root [2018-05-27 11:55:10,997] - Forwarding logs to logger[192.168.0.104:50960/0/0/0]...
 ERROR root [2018-05-27 11:57:18,895] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:57:18,903] - The following logs sent to logger failed:
  WARN root [2018-05-27 11:57:18,903] - ==> [2018-05-27 11:57:18 889] TCPPacketReceiver::processPendingEvents(192.168.0.104:50960): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:57:18,904] - ==> [2018-05-27 11:57:18 895] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 11:57:18,955] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50966): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 11:57:18,962] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 11:57:18,967] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 11:57:18,967] - onLoginAppShutDown()
  INFO root [2018-05-27 11:57:18,967] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 11:57:18,967] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:57:18,968] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:57:18,977] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 11:57:18,977] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 11:57:20,155] - 
  INFO root [2018-05-27 11:57:20,156] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 11:57:20,156] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 11:57:20,157] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 11:57:20,157] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 11:57:20,166] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 11:57:20,166] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 11:57:20,167] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51062 )
  INFO root [2018-05-27 11:57:20,167] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51062, SOMAXCONN=128.
  INFO root [2018-05-27 11:57:20,168] - server-configs:
  INFO root [2018-05-27 11:57:20,168] - 	internalAddr : 192.168.0.104:51062
  INFO root [2018-05-27 11:57:20,168] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 11:57:20,168] - 	componentID : 9000
  WARN root [2018-05-27 11:57:20,680] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20156, errorno=10048
  INFO root [2018-05-27 11:57:20,683] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 10428. PID: 7628 ----
  INFO root [2018-05-27 11:57:20,684] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 11:57:20,684] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 11:57:20,684] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 11:57:20,813] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 11:57:20,814] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 11:57:20,814] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 11:57:20,817] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 11:57:20,817] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 11:57:20,817] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 11:57:20,818] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 11:57:20,848] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 11:57:20,879] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 11:57:20,879] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 11:57:20,881] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 11:57:20,881] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 11:57:21,155] - ---- loginapp is running ----
 DEBUG root [2018-05-27 11:57:21,156] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 11:57:28,242] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 11:57:28,273] - Components::findComponents: found logger, addr:192.168.0.104:51061
  INFO root [2018-05-27 11:57:28,273] - Components::addComponent: reset orderLog, uid=10428!
  INFO root [2018-05-27 11:57:28,274] - Components::addComponent[logger], uid=10428, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:57:28,280] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 11:57:28,379] - Components::findComponents: found dbmgr, addr:192.168.0.104:51063
  INFO root [2018-05-27 11:57:28,379] - Components::addComponent: reset orderLog, uid=10428!
  INFO root [2018-05-27 11:57:28,380] - Components::addComponent[dbmgr], uid=10428, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 11:57:28,381] - Components::findComponents: found dbmgr, addr:192.168.0.104:51063
  WARN root [2018-05-27 11:57:29,381] - Forwarding logs to logger[192.168.0.104:51061/0/0/0]...
 ERROR root [2018-05-27 12:00:37,653] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:00:37,664] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:00:37,664] - ==> [2018-05-27 12:00:37 651] TCPPacketReceiver::processPendingEvents(192.168.0.104:51061): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:00:37,664] - ==> [2018-05-27 12:00:37 654] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:00:37,716] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51063): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:00:37,719] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:00:37,727] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:00:37,729] - onLoginAppShutDown()
  INFO root [2018-05-27 12:00:37,729] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:00:37,730] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:00:37,730] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:00:37,739] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:00:37,739] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:00:38,920] - 
  INFO root [2018-05-27 12:00:38,921] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:00:38,921] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:00:38,922] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:00:38,922] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:00:38,924] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:00:38,925] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:00:38,926] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51149 )
  INFO root [2018-05-27 12:00:38,926] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51149, SOMAXCONN=128.
  INFO root [2018-05-27 12:00:38,926] - server-configs:
  INFO root [2018-05-27 12:00:38,926] - 	internalAddr : 192.168.0.104:51149
  INFO root [2018-05-27 12:00:38,926] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:00:38,926] - 	componentID : 9000
  INFO root [2018-05-27 12:00:40,645] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 11077. PID: 14212 ----
  INFO root [2018-05-27 12:00:40,646] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:00:40,646] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:00:40,646] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:00:40,769] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:00:40,769] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:00:40,769] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:00:40,772] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:00:40,772] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:00:40,773] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:00:40,773] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:00:40,801] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:00:40,837] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:00:40,837] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:00:40,839] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:00:40,840] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:00:41,150] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:00:41,151] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:00:48,260] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:00:48,271] - Components::findComponents: found logger, addr:192.168.0.104:51147
  INFO root [2018-05-27 12:00:48,271] - Components::addComponent: reset orderLog, uid=11077!
  INFO root [2018-05-27 12:00:48,272] - Components::addComponent[logger], uid=11077, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:00:48,275] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:00:48,374] - Components::findComponents: found dbmgr, addr:192.168.0.104:51152
  INFO root [2018-05-27 12:00:48,375] - Components::addComponent: reset orderLog, uid=11077!
  INFO root [2018-05-27 12:00:48,375] - Components::addComponent[dbmgr], uid=11077, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:00:48,375] - Components::findComponents: found dbmgr, addr:192.168.0.104:51152
  WARN root [2018-05-27 12:00:49,376] - Forwarding logs to logger[192.168.0.104:51147/0/0/0]...
 ERROR root [2018-05-27 12:02:02,709] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:02:02,719] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:02:02,719] - ==> [2018-05-27 12:02:02 707] TCPPacketReceiver::processPendingEvents(192.168.0.104:51147): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:02:02,719] - ==> [2018-05-27 12:02:02 709] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:02:02,771] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51152): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:02:02,774] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:02:02,783] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:02:02,785] - onLoginAppShutDown()
  INFO root [2018-05-27 12:02:02,785] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:02:02,785] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:02:02,785] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:02:02,785] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:02:02,785] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:02:02,785] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:02:02,785] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:02:02,785] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:02:02,786] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:02:02,786] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:02:02,794] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:02:02,794] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:02:07,003] - 
  INFO root [2018-05-27 12:02:07,007] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:02:07,008] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:02:07,008] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:02:07,008] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:02:07,014] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:02:07,014] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:02:07,016] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51222 )
  INFO root [2018-05-27 12:02:07,016] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51222, SOMAXCONN=128.
  INFO root [2018-05-27 12:02:07,016] - server-configs:
  INFO root [2018-05-27 12:02:07,016] - 	internalAddr : 192.168.0.104:51222
  INFO root [2018-05-27 12:02:07,016] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:02:07,016] - 	componentID : 9000
  INFO root [2018-05-27 12:02:08,727] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 11365. PID: 13040 ----
  INFO root [2018-05-27 12:02:08,728] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:02:08,728] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:02:08,728] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:02:08,850] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:02:08,850] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:02:08,851] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:02:08,854] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:02:08,854] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:02:08,854] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:02:08,855] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:02:08,883] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:02:08,913] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:02:08,914] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:02:08,915] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:02:08,915] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:02:09,217] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:02:09,217] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:02:16,336] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:02:16,347] - Components::findComponents: found logger, addr:192.168.0.104:51227
  INFO root [2018-05-27 12:02:16,348] - Components::addComponent: reset orderLog, uid=11365!
  INFO root [2018-05-27 12:02:16,348] - Components::addComponent[logger], uid=11365, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:02:16,350] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:02:16,451] - Components::findComponents: found dbmgr, addr:192.168.0.104:51223
  INFO root [2018-05-27 12:02:16,451] - Components::addComponent: reset orderLog, uid=11365!
  INFO root [2018-05-27 12:02:16,451] - Components::addComponent[dbmgr], uid=11365, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:02:16,451] - Components::findComponents: found dbmgr, addr:192.168.0.104:51223
  WARN root [2018-05-27 12:02:17,451] - Forwarding logs to logger[192.168.0.104:51227/0/0/0]...
 ERROR root [2018-05-27 12:02:56,098] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:02:56,110] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:02:56,110] - ==> [2018-05-27 12:02:56 096] TCPPacketReceiver::processPendingEvents(192.168.0.104:51227): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:02:56,110] - ==> [2018-05-27 12:02:56 098] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:02:56,162] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51223): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:02:56,164] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:02:56,173] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:02:56,174] - onLoginAppShutDown()
  INFO root [2018-05-27 12:02:56,174] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:02:56,174] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:02:56,174] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:02:56,174] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:02:56,174] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:02:56,174] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:02:56,175] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:02:56,175] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:02:56,175] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:02:56,175] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:02:56,184] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:02:56,184] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:02:57,405] - 
  INFO root [2018-05-27 12:02:57,405] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:02:57,406] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:02:57,406] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:02:57,406] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:02:57,409] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:02:57,409] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:02:57,410] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51262 )
  INFO root [2018-05-27 12:02:57,410] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51262, SOMAXCONN=128.
  INFO root [2018-05-27 12:02:57,411] - server-configs:
  INFO root [2018-05-27 12:02:57,411] - 	internalAddr : 192.168.0.104:51262
  INFO root [2018-05-27 12:02:57,411] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:02:57,411] - 	componentID : 9000
  INFO root [2018-05-27 12:02:59,113] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 11528. PID: 11908 ----
  INFO root [2018-05-27 12:02:59,114] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:02:59,114] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:02:59,114] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:02:59,244] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:02:59,245] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:02:59,245] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:02:59,249] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:02:59,250] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:02:59,250] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:02:59,251] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:02:59,283] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:02:59,314] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:02:59,315] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:02:59,316] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:02:59,317] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:02:59,636] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:02:59,636] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:03:02,093] - 
  INFO root [2018-05-27 12:03:02,099] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:03:02,100] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:03:02,100] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:03:02,100] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:03:02,106] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:03:02,106] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:03:02,108] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51272 )
  INFO root [2018-05-27 12:03:02,108] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51272, SOMAXCONN=128.
  INFO root [2018-05-27 12:03:02,108] - server-configs:
  INFO root [2018-05-27 12:03:02,108] - 	internalAddr : 192.168.0.104:51272
  INFO root [2018-05-27 12:03:02,108] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:03:02,108] - 	componentID : 9000
  WARN root [2018-05-27 12:03:02,629] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20954, errorno=10048
  INFO root [2018-05-27 12:03:02,633] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 11544. PID: 15008 ----
  INFO root [2018-05-27 12:03:02,633] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:03:02,633] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:03:02,634] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:03:02,758] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:03:02,758] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:03:02,759] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:03:02,763] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:03:02,763] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:03:02,764] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:03:02,764] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:03:02,793] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:03:02,823] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:03:02,823] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:03:02,825] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:03:02,825] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:03:03,132] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:03:03,132] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:03:10,245] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:03:10,313] - Components::findComponents: found logger, addr:192.168.0.104:51278
  INFO root [2018-05-27 12:03:10,314] - Components::addComponent: reset orderLog, uid=11544!
  INFO root [2018-05-27 12:03:10,314] - Components::addComponent[logger], uid=11544, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:03:10,315] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:03:10,420] - Components::findComponents: found dbmgr, addr:192.168.0.104:51271
  INFO root [2018-05-27 12:03:10,420] - Components::addComponent: reset orderLog, uid=11544!
  INFO root [2018-05-27 12:03:10,420] - Components::addComponent[dbmgr], uid=11544, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:03:10,421] - Components::findComponents: found dbmgr, addr:192.168.0.104:51271
  WARN root [2018-05-27 12:03:11,421] - Forwarding logs to logger[192.168.0.104:51278/0/0/0]...
 ERROR root [2018-05-27 12:03:31,223] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:03:31,232] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:03:31,232] - ==> [2018-05-27 12:03:31 218] TCPPacketReceiver::processPendingEvents(192.168.0.104:51278): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:03:31,232] - ==> [2018-05-27 12:03:31 224] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:03:31,282] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51271): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:03:31,284] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:03:31,294] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:03:31,297] - onLoginAppShutDown()
  INFO root [2018-05-27 12:03:31,297] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:03:31,297] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:03:31,297] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:03:31,297] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:03:31,298] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:03:31,298] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:03:31,298] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:03:31,298] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:03:31,298] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:03:31,298] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:03:31,307] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:03:31,307] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:03:32,494] - 
  INFO root [2018-05-27 12:03:32,495] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:03:32,496] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:03:32,496] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:03:32,496] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:03:32,499] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:03:32,499] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:03:32,501] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51315 )
  INFO root [2018-05-27 12:03:32,501] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51315, SOMAXCONN=128.
  INFO root [2018-05-27 12:03:32,501] - server-configs:
  INFO root [2018-05-27 12:03:32,501] - 	internalAddr : 192.168.0.104:51315
  INFO root [2018-05-27 12:03:32,501] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:03:32,501] - 	componentID : 9000
  WARN root [2018-05-27 12:03:33,010] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20887, errorno=10048
  INFO root [2018-05-27 12:03:33,014] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 11646. PID: 14592 ----
  INFO root [2018-05-27 12:03:33,014] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:03:33,014] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:03:33,014] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:03:33,145] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:03:33,146] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:03:33,147] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:03:33,150] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:03:33,150] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:03:33,150] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:03:33,151] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:03:33,181] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:03:33,210] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:03:33,210] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:03:33,212] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:03:33,212] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:03:33,496] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:03:33,497] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:03:40,573] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:03:40,613] - Components::findComponents: found logger, addr:192.168.0.104:51311
  INFO root [2018-05-27 12:03:40,614] - Components::addComponent: reset orderLog, uid=11646!
  INFO root [2018-05-27 12:03:40,614] - Components::addComponent[logger], uid=11646, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:03:40,615] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:03:40,717] - Components::findComponents: found dbmgr, addr:192.168.0.104:51308
  INFO root [2018-05-27 12:03:40,718] - Components::addComponent: reset orderLog, uid=11646!
  INFO root [2018-05-27 12:03:40,718] - Components::addComponent[dbmgr], uid=11646, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:03:40,718] - Components::findComponents: found dbmgr, addr:192.168.0.104:51308
  WARN root [2018-05-27 12:03:41,718] - Forwarding logs to logger[192.168.0.104:51311/0/0/0]...
 ERROR root [2018-05-27 12:16:31,418] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:16:31,428] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:16:31,428] - ==> [2018-05-27 12:16:31 416] TCPPacketReceiver::processPendingEvents(192.168.0.104:51311): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:16:31,429] - ==> [2018-05-27 12:16:31 418] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:16:31,483] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51308): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:16:31,485] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:16:31,493] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:16:31,495] - onLoginAppShutDown()
  INFO root [2018-05-27 12:16:31,495] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:16:31,495] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:16:31,495] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:16:31,495] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:16:31,495] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:16:31,495] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:16:31,495] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:16:31,495] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:16:31,496] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:16:31,496] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:16:31,505] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:16:31,506] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:16:32,692] - 
  INFO root [2018-05-27 12:16:32,693] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:16:32,694] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:16:32,694] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:16:32,694] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:16:32,707] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:16:32,708] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:16:32,710] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51486 )
  INFO root [2018-05-27 12:16:32,710] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51486, SOMAXCONN=128.
  INFO root [2018-05-27 12:16:32,710] - server-configs:
  INFO root [2018-05-27 12:16:32,710] - 	internalAddr : 192.168.0.104:51486
  INFO root [2018-05-27 12:16:32,710] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:16:32,710] - 	componentID : 9000
  WARN root [2018-05-27 12:16:33,220] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20582, errorno=10048
  INFO root [2018-05-27 12:16:33,227] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 14193. PID: 13408 ----
  INFO root [2018-05-27 12:16:33,227] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:16:33,227] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:16:33,227] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:16:33,356] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:16:33,356] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:16:33,357] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:16:33,361] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:16:33,361] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:16:33,361] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:16:33,362] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:16:33,393] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:16:33,425] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:16:33,425] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:16:33,427] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:16:33,427] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:16:33,722] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:16:33,722] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:16:40,828] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:16:40,917] - Components::findComponents: found logger, addr:192.168.0.104:51487
  INFO root [2018-05-27 12:16:40,917] - Components::addComponent: reset orderLog, uid=14193!
  INFO root [2018-05-27 12:16:40,918] - Components::addComponent[logger], uid=14193, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:16:40,919] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:16:41,019] - Components::findComponents: found dbmgr, addr:192.168.0.104:51482
  INFO root [2018-05-27 12:16:41,019] - Components::addComponent: reset orderLog, uid=14193!
  INFO root [2018-05-27 12:16:41,019] - Components::addComponent[dbmgr], uid=14193, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:16:41,019] - Components::findComponents: found dbmgr, addr:192.168.0.104:51482
  WARN root [2018-05-27 12:16:42,019] - Forwarding logs to logger[192.168.0.104:51487/0/0/0]...
 ERROR root [2018-05-27 12:42:17,790] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:42:17,797] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:42:17,798] - ==> [2018-05-27 12:42:17 787] TCPPacketReceiver::processPendingEvents(192.168.0.104:51487): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:42:17,798] - ==> [2018-05-27 12:42:17 790] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:42:17,850] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51482): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:42:17,854] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:42:17,857] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:42:17,861] - onLoginAppShutDown()
  INFO root [2018-05-27 12:42:17,861] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:42:17,861] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:42:17,861] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:42:17,861] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:42:17,861] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:42:17,861] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:42:17,861] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:42:17,862] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:42:17,862] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:42:17,862] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:42:17,870] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:42:17,870] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:42:19,076] - 
  INFO root [2018-05-27 12:42:19,081] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:42:19,082] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:42:19,082] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:42:19,082] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:42:19,091] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:42:19,091] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:42:19,093] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51762 )
  INFO root [2018-05-27 12:42:19,093] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51762, SOMAXCONN=128.
  INFO root [2018-05-27 12:42:19,093] - server-configs:
  INFO root [2018-05-27 12:42:19,094] - 	internalAddr : 192.168.0.104:51762
  INFO root [2018-05-27 12:42:19,094] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:42:19,094] - 	componentID : 9000
  INFO root [2018-05-27 12:42:20,793] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 19241. PID: 11776 ----
  INFO root [2018-05-27 12:42:20,794] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:42:20,794] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:42:20,794] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:42:20,918] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:42:20,918] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:42:20,918] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:42:20,923] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:42:20,923] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:42:20,923] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:42:20,924] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:42:20,955] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:42:20,986] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:42:20,986] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:42:20,987] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:42:20,988] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:42:21,274] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:42:21,274] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:42:28,388] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:42:28,479] - Components::findComponents: found logger, addr:192.168.0.104:51759
  INFO root [2018-05-27 12:42:28,479] - Components::addComponent: reset orderLog, uid=19241!
  INFO root [2018-05-27 12:42:28,480] - Components::addComponent[logger], uid=19241, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:42:28,481] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:42:28,584] - Components::findComponents: found dbmgr, addr:192.168.0.104:51758
  INFO root [2018-05-27 12:42:28,585] - Components::addComponent: reset orderLog, uid=19241!
  INFO root [2018-05-27 12:42:28,585] - Components::addComponent[dbmgr], uid=19241, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:42:28,585] - Components::findComponents: found dbmgr, addr:192.168.0.104:51758
  WARN root [2018-05-27 12:42:29,585] - Forwarding logs to logger[192.168.0.104:51759/0/0/0]...
 ERROR root [2018-05-27 12:47:28,192] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:47:28,200] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:47:28,200] - ==> [2018-05-27 12:47:28 190] TCPPacketReceiver::processPendingEvents(192.168.0.104:51759): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:47:28,200] - ==> [2018-05-27 12:47:28 193] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:47:28,259] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51758): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:47:28,263] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:47:28,277] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:47:28,277] - onLoginAppShutDown()
  INFO root [2018-05-27 12:47:28,277] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:47:28,277] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:47:28,278] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:47:28,286] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:47:28,287] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:47:29,492] - 
  INFO root [2018-05-27 12:47:29,493] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:47:29,494] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:47:29,494] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:47:29,494] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:47:29,500] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:47:29,501] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:47:29,502] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51845 )
  INFO root [2018-05-27 12:47:29,502] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51845, SOMAXCONN=128.
  INFO root [2018-05-27 12:47:29,502] - server-configs:
  INFO root [2018-05-27 12:47:29,502] - 	internalAddr : 192.168.0.104:51845
  INFO root [2018-05-27 12:47:29,502] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:47:29,502] - 	componentID : 9000
  INFO root [2018-05-27 12:47:31,230] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 20257. PID: 12948 ----
  INFO root [2018-05-27 12:47:31,231] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:47:31,231] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:47:31,231] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:47:31,357] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:47:31,358] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:47:31,358] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:47:31,363] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:47:31,363] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:47:31,363] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:47:31,364] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:47:31,402] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:47:31,441] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:47:31,441] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:47:31,443] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:47:31,444] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:47:31,772] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:47:31,772] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:47:38,905] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:47:38,917] - Components::findComponents: found logger, addr:192.168.0.104:51850
  INFO root [2018-05-27 12:47:38,917] - Components::addComponent: reset orderLog, uid=20257!
  INFO root [2018-05-27 12:47:38,917] - Components::addComponent[logger], uid=20257, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:47:38,918] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:47:39,019] - Components::findComponents: found dbmgr, addr:192.168.0.104:51843
  INFO root [2018-05-27 12:47:39,019] - Components::addComponent: reset orderLog, uid=20257!
  INFO root [2018-05-27 12:47:39,019] - Components::addComponent[dbmgr], uid=20257, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:47:39,019] - Components::findComponents: found dbmgr, addr:192.168.0.104:51843
  WARN root [2018-05-27 12:47:40,020] - Forwarding logs to logger[192.168.0.104:51850/0/0/0]...
 ERROR root [2018-05-27 12:52:43,206] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:52:43,219] - The following logs sent to logger failed:
  WARN root [2018-05-27 12:52:43,219] - ==> [2018-05-27 12:52:43 204] TCPPacketReceiver::processPendingEvents(192.168.0.104:51850): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:52:43,219] - ==> [2018-05-27 12:52:43 207] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 12:52:43,277] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51843): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 12:52:43,280] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 12:52:43,295] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 12:52:43,296] - onLoginAppShutDown()
  INFO root [2018-05-27 12:52:43,296] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 12:52:43,296] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:52:43,297] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:52:43,306] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 12:52:43,306] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 12:52:44,536] - 
  INFO root [2018-05-27 12:52:44,536] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 12:52:44,537] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 12:52:44,537] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 12:52:44,537] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 12:52:44,540] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 12:52:44,540] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 12:52:44,541] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51910 )
  INFO root [2018-05-27 12:52:44,542] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51910, SOMAXCONN=128.
  INFO root [2018-05-27 12:52:44,542] - server-configs:
  INFO root [2018-05-27 12:52:44,542] - 	internalAddr : 192.168.0.104:51910
  INFO root [2018-05-27 12:52:44,542] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 12:52:44,542] - 	componentID : 9000
  WARN root [2018-05-27 12:52:45,072] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20262, errorno=10048
  INFO root [2018-05-27 12:52:45,076] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 21286. PID: 16052 ----
  INFO root [2018-05-27 12:52:45,076] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 12:52:45,076] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 12:52:45,076] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 12:52:45,205] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 12:52:45,205] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 12:52:45,206] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 12:52:45,209] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 12:52:45,210] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 12:52:45,210] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 12:52:45,210] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 12:52:45,243] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 12:52:45,272] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 12:52:45,272] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 12:52:45,274] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 12:52:45,274] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 12:52:45,552] - ---- loginapp is running ----
 DEBUG root [2018-05-27 12:52:45,553] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 12:52:52,675] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 12:52:52,778] - Components::findComponents: found logger, addr:192.168.0.104:51907
  INFO root [2018-05-27 12:52:52,779] - Components::addComponent: reset orderLog, uid=21286!
  INFO root [2018-05-27 12:52:52,780] - Components::addComponent[logger], uid=21286, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:52:52,782] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 12:52:52,882] - Components::findComponents: found dbmgr, addr:192.168.0.104:51905
  INFO root [2018-05-27 12:52:52,882] - Components::addComponent: reset orderLog, uid=21286!
  INFO root [2018-05-27 12:52:52,882] - Components::addComponent[dbmgr], uid=21286, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 12:52:52,883] - Components::findComponents: found dbmgr, addr:192.168.0.104:51905
  WARN root [2018-05-27 12:52:53,883] - Forwarding logs to logger[192.168.0.104:51907/0/0/0]...
 ERROR root [2018-05-27 13:02:37,466] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:02:37,472] - The following logs sent to logger failed:
  WARN root [2018-05-27 13:02:37,473] - ==> [2018-05-27 13:02:37 457] TCPPacketReceiver::processPendingEvents(192.168.0.104:51907): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:02:37,473] - ==> [2018-05-27 13:02:37 466] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 13:02:37,525] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51905): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:02:37,532] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:02:37,539] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 13:02:37,542] - onLoginAppShutDown()
  INFO root [2018-05-27 13:02:37,542] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 13:02:37,542] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 13:02:37,542] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:02:37,542] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:02:37,542] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:02:37,542] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:02:37,542] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:02:37,542] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:02:37,543] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:02:37,543] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:02:37,551] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 13:02:37,551] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 13:02:38,771] - 
  INFO root [2018-05-27 13:02:38,772] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 13:02:38,773] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 13:02:38,773] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 13:02:38,773] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 13:02:38,776] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 13:02:38,776] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 13:02:38,777] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52029 )
  INFO root [2018-05-27 13:02:38,778] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52029, SOMAXCONN=128.
  INFO root [2018-05-27 13:02:38,778] - server-configs:
  INFO root [2018-05-27 13:02:38,778] - 	internalAddr : 192.168.0.104:52029
  INFO root [2018-05-27 13:02:38,778] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 13:02:38,778] - 	componentID : 9000
  INFO root [2018-05-27 13:02:40,482] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 23225. PID: 1948 ----
  INFO root [2018-05-27 13:02:40,483] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 13:02:40,483] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 13:02:40,483] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 13:02:40,606] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:02:40,606] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:02:40,607] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:02:40,610] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:02:40,610] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:02:40,610] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:02:40,611] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:02:40,639] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:02:40,667] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 13:02:40,667] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 13:02:40,669] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 13:02:40,669] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 13:02:40,974] - ---- loginapp is running ----
 DEBUG root [2018-05-27 13:02:40,974] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 13:02:48,090] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 13:02:48,155] - Components::findComponents: found logger, addr:192.168.0.104:52023
  INFO root [2018-05-27 13:02:48,156] - Components::addComponent: reset orderLog, uid=23225!
  INFO root [2018-05-27 13:02:48,157] - Components::addComponent[logger], uid=23225, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:02:48,159] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 13:02:48,262] - Components::findComponents: found dbmgr, addr:192.168.0.104:52024
  INFO root [2018-05-27 13:02:48,263] - Components::addComponent: reset orderLog, uid=23225!
  INFO root [2018-05-27 13:02:48,263] - Components::addComponent[dbmgr], uid=23225, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:02:48,263] - Components::findComponents: found dbmgr, addr:192.168.0.104:52024
  WARN root [2018-05-27 13:02:49,263] - Forwarding logs to logger[192.168.0.104:52023/0/0/0]...
 ERROR root [2018-05-27 13:08:32,906] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:08:32,913] - The following logs sent to logger failed:
  WARN root [2018-05-27 13:08:32,914] - ==> [2018-05-27 13:08:32 899] TCPPacketReceiver::processPendingEvents(192.168.0.104:52023): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:08:32,914] - ==> [2018-05-27 13:08:32 907] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 13:08:32,971] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52024): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:08:32,973] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:08:32,985] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 13:08:32,987] - onLoginAppShutDown()
  INFO root [2018-05-27 13:08:32,987] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 13:08:32,987] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 13:08:32,987] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:08:32,987] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:08:32,987] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:08:32,987] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:08:32,988] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:08:32,988] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:08:32,988] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:08:32,988] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:08:32,996] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 13:08:32,996] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 13:08:34,209] - 
  INFO root [2018-05-27 13:08:34,210] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 13:08:34,210] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 13:08:34,210] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 13:08:34,210] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 13:08:34,220] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 13:08:34,221] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 13:08:34,222] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52288 )
  INFO root [2018-05-27 13:08:34,223] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52288, SOMAXCONN=128.
  INFO root [2018-05-27 13:08:34,223] - server-configs:
  INFO root [2018-05-27 13:08:34,223] - 	internalAddr : 192.168.0.104:52288
  INFO root [2018-05-27 13:08:34,223] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 13:08:34,223] - 	componentID : 9000
  INFO root [2018-05-27 13:08:35,923] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 24385. PID: 8172 ----
  INFO root [2018-05-27 13:08:35,924] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 13:08:35,924] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 13:08:35,924] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 13:08:36,051] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:08:36,051] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:08:36,052] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:08:36,055] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:08:36,055] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:08:36,055] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:08:36,055] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:08:36,088] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:08:36,126] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 13:08:36,126] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 13:08:36,129] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 13:08:36,129] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 13:08:36,438] - ---- loginapp is running ----
 DEBUG root [2018-05-27 13:08:36,438] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 13:08:43,589] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 13:08:43,690] - Components::findComponents: found logger, addr:192.168.0.104:52292
  INFO root [2018-05-27 13:08:43,690] - Components::addComponent: reset orderLog, uid=24385!
  INFO root [2018-05-27 13:08:43,691] - Components::addComponent[logger], uid=24385, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:08:43,693] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 13:08:43,795] - Components::findComponents: found dbmgr, addr:192.168.0.104:52287
  INFO root [2018-05-27 13:08:43,796] - Components::addComponent: reset orderLog, uid=24385!
  INFO root [2018-05-27 13:08:43,797] - Components::addComponent[dbmgr], uid=24385, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:08:43,797] - Components::findComponents: found dbmgr, addr:192.168.0.104:52287
  WARN root [2018-05-27 13:08:44,797] - Forwarding logs to logger[192.168.0.104:52292/0/0/0]...
 ERROR root [2018-05-27 13:10:34,873] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:10:34,887] - The following logs sent to logger failed:
  WARN root [2018-05-27 13:10:34,887] - ==> [2018-05-27 13:10:34 870] TCPPacketReceiver::processPendingEvents(192.168.0.104:52292): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:10:34,887] - ==> [2018-05-27 13:10:34 873] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 13:10:34,941] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52287): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:10:34,951] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:10:34,959] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 13:10:34,962] - onLoginAppShutDown()
  INFO root [2018-05-27 13:10:34,962] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 13:10:34,962] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:10:34,963] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:10:34,971] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 13:10:34,971] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 13:10:36,181] - 
  INFO root [2018-05-27 13:10:36,182] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 13:10:36,183] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 13:10:36,183] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 13:10:36,183] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 13:10:36,188] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 13:10:36,188] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 13:10:36,189] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52342 )
  INFO root [2018-05-27 13:10:36,190] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52342, SOMAXCONN=128.
  INFO root [2018-05-27 13:10:36,190] - server-configs:
  INFO root [2018-05-27 13:10:36,190] - 	internalAddr : 192.168.0.104:52342
  INFO root [2018-05-27 13:10:36,190] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 13:10:36,190] - 	componentID : 9000
  INFO root [2018-05-27 13:10:37,877] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 24783. PID: 15496 ----
  INFO root [2018-05-27 13:10:37,878] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 13:10:37,878] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 13:10:37,878] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 13:10:38,003] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:10:38,004] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:10:38,004] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:10:38,007] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:10:38,007] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:10:38,007] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:10:38,008] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:10:38,040] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:10:38,070] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 13:10:38,070] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 13:10:38,072] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 13:10:38,072] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 13:10:38,352] - ---- loginapp is running ----
 DEBUG root [2018-05-27 13:10:38,352] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 13:10:45,452] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 13:10:45,461] - Components::findComponents: found logger, addr:192.168.0.104:52340
  INFO root [2018-05-27 13:10:45,461] - Components::addComponent: reset orderLog, uid=24783!
  INFO root [2018-05-27 13:10:45,462] - Components::addComponent[logger], uid=24783, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:10:45,462] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 13:10:45,463] - Components::findComponents: found logger, addr:192.168.0.104:52340
  INFO root [2018-05-27 13:10:45,566] - Components::findComponents: found dbmgr, addr:192.168.0.104:52344
  INFO root [2018-05-27 13:10:45,566] - Components::addComponent: reset orderLog, uid=24783!
  INFO root [2018-05-27 13:10:45,566] - Components::addComponent[dbmgr], uid=24783, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:10:45,566] - Components::findComponents: found dbmgr, addr:192.168.0.104:52344
  WARN root [2018-05-27 13:10:46,566] - Forwarding logs to logger[192.168.0.104:52340/0/0/0]...
 ERROR root [2018-05-27 13:13:45,514] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:13:45,523] - The following logs sent to logger failed:
  WARN root [2018-05-27 13:13:45,523] - ==> [2018-05-27 13:13:45 512] TCPPacketReceiver::processPendingEvents(192.168.0.104:52340): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:13:45,523] - ==> [2018-05-27 13:13:45 515] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 13:13:45,585] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52344): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:13:45,588] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:13:45,601] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 13:13:45,602] - onLoginAppShutDown()
  INFO root [2018-05-27 13:13:45,602] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 13:13:45,602] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:13:45,603] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:13:45,612] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 13:13:45,612] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 13:13:46,835] - 
  INFO root [2018-05-27 13:13:46,836] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 13:13:46,836] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 13:13:46,836] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 13:13:46,837] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 13:13:46,839] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 13:13:46,840] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 13:13:46,841] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52397 )
  INFO root [2018-05-27 13:13:46,841] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52397, SOMAXCONN=128.
  INFO root [2018-05-27 13:13:46,841] - server-configs:
  INFO root [2018-05-27 13:13:46,841] - 	internalAddr : 192.168.0.104:52397
  INFO root [2018-05-27 13:13:46,841] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 13:13:46,841] - 	componentID : 9000
  INFO root [2018-05-27 13:13:48,555] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 25407. PID: 14412 ----
  INFO root [2018-05-27 13:13:48,556] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 13:13:48,556] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 13:13:48,556] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 13:13:48,680] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:13:48,681] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:13:48,681] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:13:48,685] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:13:48,685] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:13:48,686] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:13:48,686] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:13:48,723] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:13:48,757] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 13:13:48,757] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 13:13:48,759] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 13:13:48,760] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 13:13:49,082] - ---- loginapp is running ----
 DEBUG root [2018-05-27 13:13:49,083] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 13:13:56,160] - Components::findComponents: find logger(1)...
  INFO root [2018-05-27 13:13:56,187] - Components::findComponents: found logger, addr:192.168.0.104:52399
  INFO root [2018-05-27 13:13:56,188] - Components::addComponent: reset orderLog, uid=25407!
  INFO root [2018-05-27 13:13:56,189] - Components::addComponent[logger], uid=25407, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:13:56,190] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-27 13:13:56,293] - Components::findComponents: found dbmgr, addr:192.168.0.104:52401
  INFO root [2018-05-27 13:13:56,294] - Components::addComponent: reset orderLog, uid=25407!
  INFO root [2018-05-27 13:13:56,294] - Components::addComponent[dbmgr], uid=25407, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:13:56,295] - Components::findComponents: found dbmgr, addr:192.168.0.104:52401
  WARN root [2018-05-27 13:13:57,295] - Forwarding logs to logger[192.168.0.104:52399/0/0/0]...
 ERROR root [2018-05-27 13:20:00,953] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:20:00,968] - The following logs sent to logger failed:
  WARN root [2018-05-27 13:20:00,968] - ==> [2018-05-27 13:20:00 949] TCPPacketReceiver::processPendingEvents(192.168.0.104:52399): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:20:00,968] - ==> [2018-05-27 13:20:00 953] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-27 13:20:01,021] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52401): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-27 13:20:01,024] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-27 13:20:01,036] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-27 13:20:01,038] - onLoginAppShutDown()
  INFO root [2018-05-27 13:20:01,038] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-27 13:20:01,038] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:20:01,039] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:20:01,047] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-27 13:20:01,047] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-27 13:20:02,277] - 
  INFO root [2018-05-27 13:20:02,279] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-27 13:20:02,280] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-27 13:20:02,280] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-27 13:20:02,280] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-27 13:20:02,284] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-27 13:20:02,284] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-27 13:20:02,285] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52482 )
  INFO root [2018-05-27 13:20:02,286] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52482, SOMAXCONN=128.
  INFO root [2018-05-27 13:20:02,286] - server-configs:
  INFO root [2018-05-27 13:20:02,286] - 	internalAddr : 192.168.0.104:52482
  INFO root [2018-05-27 13:20:02,286] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-27 13:20:02,286] - 	componentID : 9000
  INFO root [2018-05-27 13:20:04,012] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26631. PID: 16048 ----
  INFO root [2018-05-27 13:20:04,013] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-27 13:20:04,013] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-27 13:20:04,013] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-27 13:20:04,136] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-27 13:20:04,137] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-27 13:20:04,137] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-27 13:20:04,140] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-27 13:20:04,140] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-27 13:20:04,141] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-27 13:20:04,141] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-27 13:20:04,174] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-27 13:20:04,214] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-27 13:20:04,215] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-27 13:20:04,217] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-27 13:20:04,218] - TelnetServer server is running on port 31000
  INFO root [2018-05-27 13:20:04,514] - ---- loginapp is running ----
 DEBUG root [2018-05-27 13:20:04,515] - Components::process(): Request for the process of identity...
  INFO root [2018-05-27 13:20:11,638] - Components::findComponents: find logger(1)...
  WARN root [2018-05-27 13:20:11,949] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20297, errorno=10048
  INFO root [2018-05-27 13:20:12,958] - Components::findComponents: find logger(2)...
  INFO root [2018-05-27 13:20:12,975] - Components::findComponents: found logger, addr:192.168.0.104:52481
  INFO root [2018-05-27 13:20:12,975] - Components::addComponent: reset orderLog, uid=26631!
  INFO root [2018-05-27 13:20:12,975] - Components::addComponent[logger], uid=26631, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:20:12,976] - Components::findComponents: find dbmgr(3)...
  INFO root [2018-05-27 13:20:13,079] - Components::findComponents: found dbmgr, addr:192.168.0.104:52478
  INFO root [2018-05-27 13:20:13,080] - Components::addComponent: reset orderLog, uid=26631!
  INFO root [2018-05-27 13:20:13,081] - Components::addComponent[dbmgr], uid=26631, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-27 13:20:13,081] - Components::findComponents: found dbmgr, addr:192.168.0.104:52478
  WARN root [2018-05-27 13:20:14,081] - Forwarding logs to logger[192.168.0.104:52481/0/0/0]...
